import type { Metadata } from "next";
import "./globals.css";
import { geistSans } from "@/lib/fonts";
import { isDevEnv } from "@/lib/utils";
import { AlertProvider } from "@/contexts/alert-context";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} antialiased ${
          isDevEnv ? "debug-screens" : ""
        }`}
      >
        <AlertProvider>{children}</AlertProvider>
      </body>
    </html>
  );
}
